### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/fagri#12]
- [x] in Hestia we use a hack to not show the tablet mode in customizer when using a laptop, we need to check why this is not working in Fagri. I think this is the code in Hestia https://github.com/Codeinwp/hestia-pro/blob/7d65f2bb32e094d130bdbca3d8924c3179be9d37/assets/sass/customizer-style.scss#L29 
This should visible on the wp.org preview for Hestia/Fagri on a laptop
- [x] decrease big title font size from 42px to 40px
- [x] add a min-height to the featured post blog ( only the half ones ) to make it look ok on the .org preview https://www.dropbox.com/s/scdkhsloddtofwo/Screenshot%202018-05-22%2018.36.04.png?dl=0
- [x] the gradient is not very visible. it more looks like a single color.
- [x] keep the categories color with their default colors ( alternating colors ), shop page too

**Comment by rodica-andronache** [comment]
https://prnt.sc/jm7fkw

**Comment by stefan-cotitosu** [comment]
@rodica-andronache please check here #16
Now it should be ok.

**Comment by rodica-andronache** [comment]
- nealiniate vertical https://prnt.sc/jmg615
- asta asa patratos trebuie sa fie https://prnt.sc/jmg5lk ?
- https://prnt.sc/jmg50x asta nu e nici centrat, nici la stanga. Cum e in hestia https://prnt.sc/jmg4u1
- https://prnt.sc/jmg3b9  aici cred ca ar trebui sa scoti
.woocommerce-page .woocommerce-info {
   background-color: rgba(44, 168, 255, 0.8);
}
nu e prea ok sa schimbi culorile de la notice-uri
si plus, aici intra in conflict cu butonul
si mai trebuie vazut si butonul ala de ce e asa grasan

- asta asa ai vrut tu sa-l pui https://prnt.sc/jmg1as ?

- https://prnt.sc/jmfzo5
