### ISSUE TITLE
Product Testing - Uncaught ReferenceError:$ is not defined

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/fagri#20]
The page loads too slow and sometimes times out.
Console error: https://prnt.sc/lksk6m

**Comment by stefan-cotitosu** [comment]
@purplecodes I've checked the issue and it happens on poopy.life only. 

Also, this is happening for other themes too on poopy.life.  

If you see errors on a local server, please let me know, or open the issue again 👍
