### ISSUE TITLE
Contact form icons color

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/fagri#9]
@stefan-cotitosu let's make the icons in all the contact forms, a bit lighter colored 
https://prnt.sc/jkjd4n to don't stand out so much

**Comment by rodica-andronache** [comment]
@stefan-cotitosu plus, there seems to be a problem here with the contact form https://demo.themeisle.com/fagri/contact-us/

**Comment by stefan-cotitosu** [comment]
@rodica-andronache I fixed that too, it's in the same PR.

https://github.com/Codeinwp/fagri/pull/8

Thank you 😄
